spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/toy?useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=true
    username: home
    password: 1234
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  hiddenmethod:
    filter:
      enabled: true
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alstjr706@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



logging:
  level:
    org:
      hibernate:
        type:
          descriptor.sql: trace
